# Version of docker-compose
version: "3"
volumes:
  postgres_data:
    driver: local
# Containers we are going to run
services:
  postgres:
    image: postg  res:13.2-alpine
    ports:
      - 5432:5432
    environment:
      # Set user/password for Postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: solcsv_dev
      # Set a path where Postgres should store the data
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
  livebook:
    image: livebook/livebook:edge
    environment:
      - LIVEBOOK_PASSWORD=solcsv-password
    volumes:
      - ./livebook:/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    network_mode: host